---

apiVersion: devopstoolkitseries.com/v1alpha1
kind: ClusterClaim
metadata:
  name: a-team-gke
  labels:
    cluster-owner: vfarcic
spec:
  id: a-team-gke
  compositionSelector:
    matchLabels:
      provider: google
      cluster: gke
  parameters:
    nodeSize: small
    minNodeCount: 1

---

apiVersion: devopstoolkitseries.com/v1alpha1
kind: GitOpsClaim
metadata:
  name: a-team-gitops
  labels:
    cluster-owner: vfarcic
spec:
  id: a-team-gitops
  compositionSelector:
    matchLabels:
      provider: argo-gcp
  parameters:
    kubeConfig:
      secretName: a-team-gke-gkecluster
      secretNamespace: crossplane-system
    gitOpsRepo: https://github.com/vfarcic/devops-toolkit-crossplane.git
