apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: dot-gitops
  annotations:
    meta.crossplane.io/maintainer: Viktor Farcic (@vfarcic)
    meta.crossplane.io/source: github.com/vfarcic/devops-toolkit-crossplane/tree/master/packages/gitops
    meta.crossplane.io/license: MIT
    meta.crossplane.io/description: Fully operational GitOps tools Argo CD and Rancher Fleet
    meta.crossplane.io/readme: A Configuration package that defines GitOps and GitOpsClaim types that can be used to provision Kubernetes clusters with fully operational GitOps tools Argo CD and Rancher Fleet
spec:
  dependsOn:
  - provider: crossplane/provider-helm
    version: ">=v0.9"
