apiVersion: devopstoolkitseries.com/v1alpha1
kind: SQLClaim
metadata:
  name: {{ .Chart.Name }}
spec:
  id: {{ .Chart.Name }}
  compositionSelector:
    matchLabels:
      provider: google
      db: mysql
  parameters:
    version: "8_0"
    size: small
  writeConnectionSecretToRef:
    name: {{ .Chart.Name }}
