apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: dot-kubernetes
  annotations:
    meta.crossplane.io/maintainer: Viktor Farcic (@vfarcic)
    meta.crossplane.io/source: github.com/vfarcic/devops-toolkit-crossplane/tree/master/packages/k8s
    meta.crossplane.io/license: MIT
    meta.crossplane.io/description: Fully operational Kubernetes clusters in AWS (EKS), Google Cloud Platform (GKE), Azure (AKS), and CIVO (CK)
    meta.crossplane.io/readme: A Configuration package that defines a CompositeCluster and ClusterClaim types that can be used to create and provision Kubernetes fully operational clusters in AWS (EKS), Google Cloud Platform (GKE), Azure (AKS), and CIVO (CK)
spec:
  dependsOn:
  # - provider: crossplane/provider-aws
  #   version: ">=v0.23.0"
  # - provider: crossplane/provider-gcp
  #   version: ">=v0.19.0"
  # - provider: crossplane/provider-jet-azure
  #   version: ">=v0.5.0"
  # - provider: crossplane/provider-digitalocean
  #   version: ">=v0.1.0"
  - provider: crossplane/provider-helm
    version: ">=v0.9.0"
  - provider: crossplane/provider-kubernetes
    version: ">=v0.4.0"
