apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: a-team-eks
spec:
  components:
  - name: a-team-eks
    type: kubernetes
    properties:
      nodeSize: medium
      minNodeCount: 3
