apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: a-team-eks
spec:
  components:
  - name: a-team-eks
    type: kubernetes
    properties:
      nodeSize: medium
      minNodeCount: 3
    traits:
    - type: gitops
      properties:
        provider: argo
        repo: https://github.com/vfarcic/devops-toolkit-crossplane.git
    - type: eksnodegroup
      properties:
        name: extra
        instanceType: t3.medium
