---

apiVersion: ec2.aws.crossplane.io/v1beta1
kind: VPC
metadata:
  name: my-db
spec:
  forProvider:
    region: us-east-1
    cidrBlock: 10.0.0.0/16
    enableDnsSupport: true
    enableDnsHostNames: true

---

apiVersion: ec2.aws.crossplane.io/v1beta1
kind: Subnet
metadata:
  name: my-db-a
  labels:
    db: my-db
    zone: us-east-1a
spec:
  forProvider:
    region: us-east-1
    availabilityZone: us-east-1a
    cidrBlock: 10.0.0.0/24
    vpcIdRef:
      name: my-db

---

apiVersion: ec2.aws.crossplane.io/v1beta1
kind: Subnet
metadata:
  name: my-db-b
  labels:
    db: my-db
    zone: us-east-1b
spec:
  forProvider:
    region: us-east-1
    availabilityZone: us-east-1b
    cidrBlock: 10.0.1.0/24
    vpcIdRef:
      name: my-db

---

apiVersion: ec2.aws.crossplane.io/v1beta1
kind: Subnet
metadata:
  name: my-db-c
  labels:
    db: my-db
    zone: us-east-1c
spec:
  forProvider:
    region: us-east-1
    availabilityZone: us-east-1c
    cidrBlock: 10.0.2.0/24
    vpcIdRef:
      name: my-db

---

apiVersion: database.aws.crossplane.io/v1beta1
kind: DBSubnetGroup
metadata:
  name: my-db
spec:
  forProvider:
    region: us-east-1
    description: I'm too lazy to write a good description
    subnetIdSelector:
      matchLabels:
        db: my-db

---

apiVersion: ec2.aws.crossplane.io/v1beta1
kind: InternetGateway
metadata:
  name: my-db
spec:
  forProvider:
    region: us-east-1
    vpcIdRef:
      name: my-db

---

apiVersion: ec2.aws.crossplane.io/v1beta1
kind: RouteTable
metadata:
  name: my-db
spec:
  forProvider:
    region: us-east-1
    vpcIdRef:
      name: my-db
    routes:
      - destinationCidrBlock: 0.0.0.0/0
        gatewayIdRef:
          name: my-db
    associations:
    - subnetIdSelector:
        matchLabels:
          db: my-db

---

apiVersion: ec2.aws.crossplane.io/v1beta1
kind: SecurityGroup
metadata:
  name: my-db
spec:
  forProvider:
    description: I am too lazy to write descriptions
    groupName: dot
    region: us-east-1
    vpcIdRef:
      name: my-db
    ingress:
    - fromPort: 5432
      toPort: 5432
      ipProtocol: tcp
      ipRanges:
      - cidrIp: "0.0.0.0/0"

---

apiVersion: database.aws.crossplane.io/v1beta1
kind: RDSInstance
metadata:
  name: my-db
spec:
  forProvider:
    region: us-east-1
    dbSubnetGroupNameRef:
      name: my-db
    vpcSecurityGroupIDRefs:
    - name: my-db
    dbInstanceClass: db.m5.large
    masterUsername: masteruser
    engine: postgres
    engineVersion: "14.1"
    skipFinalSnapshotBeforeDeletion: true
    publiclyAccessible: true
    allocatedStorage: 200
  writeConnectionSecretToRef:
    namespace: crossplane-system
    name: my-db-sql
