---

apiVersion: v1
kind: Secret
metadata:
  name: my-db-password
data:
  password: T1QrOXZQcDhMdXhoeFVQWVpLSk1kUG1YM04xTzBTd3YzWG5ZVjI0UFZzcz0=

---

apiVersion: devopstoolkitseries.com/v1alpha1
kind: SQLClaim
metadata:
  name: my-db
spec:
  id: my-db
  compositionSelector:
    matchLabels:
      provider: azure-official
      db: postgresql
  parameters:
    version: "11"
    size: small
  writeConnectionSecretToRef:
    name: my-db
