apiVersion: databases.schemahero.io/v1alpha4
kind: Database
metadata:
  name: my-db
spec:
  immediateDeploy: true
  connection:
    postgres:
      uri:
        valueFrom:
          secretKeyRef:
            name: my-db-uri
            key: value

---

apiVersion: schemas.schemahero.io/v1alpha4
kind: Table
metadata:
  name: videos
spec:
  database: my-db
  name: videos
  schema:
    postgres:
      primaryKey:
      - id
      columns:
      - name: id
        type: text
        constraints:
          notNull: true
      - name: title
        type: text
        constraints:
          notNull: true
