apiVersion: compute.do.crossplane.io/v1alpha1
kind: Droplet
metadata:
  name: my-vm
spec:
  forProvider:
    region: nyc1
    size: s-1vcpu-1gb
    image: ubuntu-20-04-x64
  providerConfigRef:
    name: crossplane-provider-do
