---

apiVersion: v1
kind: Secret
metadata:
  namespace: crossplane-system
  name: do-creds
type: Opaque
data:
  token: MY_CREDS

---

apiVersion: do.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: crossplane-provider-do
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: do-creds
      key: token
